spring:
  profiles:
    active: local
#    include: secret
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kotudy__refactor?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: kotudy
    password: kotudy1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace

jwt:
  token:
    secretKey: 1q2w3e4r1q2w3e4r1q2w3e4r1q2w3e4r1q2w3e4r1q2w3e4r1q2w3e4r1q2w3e4r1q2w3e4r1q2w3e4r1q2w3e4r1q2w3e4r1q2w3e4r
    expire-length: '#{1000 * 60 * 60}'