= Kotudy API 명세
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:sectnums:
:docinfo: shared-head

== 회원

=== 회원가입
==== 성공
operation::MemberAuth-join-200[snippets='http-request,http-response,request-fields,response-fields']
==== 실패
===== 중복된 회원의 username일 경우
operation::MemberAuth-join-4xx[snippets='http-request,http-response,response-fields']

=== 로그인
==== 성공
operation::MemberAuth-login-200[snippets='http-request,http-response,request-fields,response-fields']
==== 실패
===== password가 회원가입 정보와 맞지 않을경우
operation::MemberAuth-login-4xx-invalid-password[snippets='http-request,http-response,response-fields']
===== 회원가입을한 username이 아닐 경우
operation::MemberAuth-login-4xx-user-not-found[snippets='http-request,http-response,response-fields']


== 단어사전

=== 한국어대사전 기반 검색
==== 성공
operation::Dictionary-word-200[snippets='http-request,http-response,request-parameters,response-fields']
==== 실패
===== 파라미터가 누락 되었을 경우
operation::Dictionary-word-5xxsnippets='http-request,http-response,response-fields']


== 나만의 단어장

=== 나만의 단어장에 추가
==== 성공
operation::MyWord-add-200[snippets='http-request,http-response,request-headers,request-fields,response-fields']
==== 실패
===== 한 회원이 중복된 단어를 저장했을 경우
operation::MyWord-add-200-already-exist[snippets='http-request,http-response,response-fields']
===== Header에 AccessToken을 넣지 않았을 경우
operation::MyWord-add-4xx-logouted[snippets='http-request,http-response,response-fields']

=== 나만의 단어장에서 삭제
==== 성공
operation::MyWord-delete-200[snippets='http-request,http-response,request-headers,response-fields']
==== 실패
===== 삭제를 요청하는 단어의 ID가 단어장에 없을 경우
operation::MyWord-delete-fail[snippets='http-request,http-response,response-fields']

=== 나만의 단어장에서 검색
==== 성공
operation::MyWord-search-200[snippets='http-request,http-response,request-headers,request-parameters,request-fields,response-fields']


== 퀴즈

=== 퀴즈 목록 생성
==== 성공
operation::Quiz-craete-200[snippets='http-request,http-response,response-fields']
==== 실패
===== 퀴즈를 만들기에 충분한 나만의 단어가 DB에 없을경우 (최소 40개)
operation::Quiz-craete-5xx[snippets='http-request,http-response,response-fields']

=== 퀴즈 결과 반영
==== 성공
operation::Quiz-patch-200[snippets='http-request,http-response,request-headers,request-fields,response-fields']
==== 실패
===== body의 형식이 문자형일 경우
operation::Quiz-patch-5xx[snippets='http-request,http-response,response-fields']


== 랭킹

=== 퀴즈 랭킹 출력 (비회원)
==== 성공
operation::QuizRankingNonMember-get-200[snippets='http-request,http-response,response-fields']
=== 퀴즈 랭킹 출력 (회원)
==== 성공
operation::QuizRanking-get-200[snippets='http-request,http-response,request-headers,response-fields']


== 오늘의 단어

=== 오늘의 단어 출력
==== 성공
operation::TodayWord-get-200[snippets='http-request,http-response,response-fields']

